/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: matisosanimation (https://sketchfab.com/matisosanimation)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/jeep-like-vehicle-97ca1fc2a00d474b8423a9774d8b5d2e
Title: Jeep-like vehicle
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Jeep(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/jeep.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.491}>
          <group name="9c3240c3da8f47f4b28fb870673ea560fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Jeep_Geo" position={[0, 0, 0.195]}>
                  <group name="L_F_Tire" position={[0.645, 0.779, 2.428]} rotation={[2.367, 0, 0]}>
                    <mesh
                      name="L_F_Tire_ruedas_0"
                      geometry={nodes.L_F_Tire_ruedas_0.geometry}
                      material={materials.ruedas}
                    />
                  </group>
                  <group
                    name="L_B_Tire"
                    position={[0.564, 0.941, -2.321]}
                    rotation={[2.374, -0.116, 0.119]}>
                    <mesh
                      name="L_B_Tire_ruedas_0"
                      geometry={nodes.L_B_Tire_ruedas_0.geometry}
                      material={materials.ruedas}
                    />
                  </group>
                  <group name="R_F_Tire" position={[-0.658, 0.779, 2.428]} rotation={[2.367, 0, 0]}>
                    <mesh
                      name="R_F_Tire_ruedas_0"
                      geometry={nodes.R_F_Tire_ruedas_0.geometry}
                      material={materials.ruedas}
                    />
                  </group>
                  <group
                    name="R_B_Tire"
                    position={[-0.601, 0.891, -2.321]}
                    rotation={[2.373, 0.114, -0.118]}>
                    <mesh
                      name="R_B_Tire_ruedas_0"
                      geometry={nodes.R_B_Tire_ruedas_0.geometry}
                      material={materials.ruedas}
                    />
                  </group>
                  <group name="Jeep_Body" position={[0, 0.047, 0]} rotation={[0.1, 0, 0]}>
                    <group name="Bulls">
                      <mesh
                        name="Bulls_ruedas_0"
                        geometry={nodes.Bulls_ruedas_0.geometry}
                        material={materials.ruedas}
                      />
                    </group>
                    <group name="Spare_Tire">
                      <mesh
                        name="Spare_Tire_ruedas_0"
                        geometry={nodes.Spare_Tire_ruedas_0.geometry}
                        material={materials.ruedas}
                      />
                    </group>
                    <group
                      name="Arma"
                      position={[0, 3.126, -1.078]}
                      rotation={[-Math.PI, 0, Math.PI]}>
                      <mesh
                        name="Arma_ruedas_0"
                        geometry={nodes.Arma_ruedas_0.geometry}
                        material={materials.ruedas}
                      />
                    </group>
                    <group name="Seat_L">
                      <mesh
                        name="Seat_L_ruedas_0"
                        geometry={nodes.Seat_L_ruedas_0.geometry}
                        material={materials.ruedas}
                      />
                    </group>
                    <group name="Seat_R">
                      <mesh
                        name="Seat_R_ruedas_0"
                        geometry={nodes.Seat_R_ruedas_0.geometry}
                        material={materials.ruedas}
                      />
                    </group>
                    <group name="puerta_L" position={[1.051, 1.883, 0.825]}>
                      <mesh
                        name="puerta_L_jeep_0"
                        geometry={nodes.puerta_L_jeep_0.geometry}
                        material={materials.jeep}
                      />
                    </group>
                    <group name="volante" position={[0.619, 2.237, 0.978]}>
                      <mesh
                        name="volante_ruedas_0"
                        geometry={nodes.volante_ruedas_0.geometry}
                        material={materials.ruedas}
                      />
                    </group>
                    <group name="Car_Body_main">
                      <mesh
                        name="Car_Body_main_jeep_0"
                        geometry={nodes.Car_Body_main_jeep_0.geometry}
                        material={materials.jeep}
                      />
                    </group>
                  </group>
                </group>
                <group name="Controls">
                  <group name="Global_Ctrl" position={[0, 0, -60]}>
                    <group name="Root_Ctrl" position={[0, 0.818, 60.195]}>
                      <group name="Top_Ctrl" position={[0, 0.051, 0]} rotation={[0.1, 0, 0]} />
                      <group name="Front_Wheel_Ctrl" position={[0, -0.039, 2.427]}>
                        <group name="L_F_Tire_Ctrl" position={[1.877, -0.019, 0.051]} />
                        <group name="R_F_Tire_Ctrl" position={[-1.876, -0.019, 0]} />
                      </group>
                      <group
                        name="L_B_Tire_Ctrl"
                        position={[1.879, 0.129, -2.312]}
                        rotation={[0, 0, -0.166]}
                      />
                      <group
                        name="R_B_Tire_Ctrl"
                        position={[-1.876, 0.079, -2.315]}
                        rotation={[0, 0, 0.164]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/jeep.glb')
